import type { Metadata } from "next";
import Providers from '@/providers/Providers';
import "./globals.css";
import Header from './../components/Header';
import SideBarContent from '../components/SideBarContent';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>

          {/* 고정 헤더 */}
          <Header />

          <div className='mt-header'></div>

          {/* 사이드바, 컨텐츠 영역 */}
          <div className='flex flex-row h-sidebar relative'>
            <div className='hidden fixed bottom-0 left-0 w-sidebar h-sidebar bg-neutral-100 shadow-md md:block'>
              <SideBarContent />
            </div>

            <div className='mr-sidebar'></div>

            <div className='flex-1'>
              {children}
            </div>
          </div>

        </Providers>
      </body>
    </html>
  );
}
