import type { Metadata } from "next";
import Providers from '@/providers/Providers';
import "./globals.css";
import Header from './../components/Header';
import SideNavBar from './../components/SideNavBar';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>

          {/* 고정 헤더 */}
          <Header />

          <div className='mt-[100px]'></div>

          {/* 사이드바, 컨텐츠 영역 */}
          <div className='flex flex-row h-[calc(100vh - 100px)] relative'>
            <div className='hidden fixed bottom-0 left-0 w-[240px] bg-blue-800 h-[calc(100vh-100px)] shadow-md md:block'>
              <SideNavBar />
            </div>

            <div className='md:mr-[240px]'></div>

            <div className='flex-1'>
              {children}
            </div>
          </div>

        </Providers>
      </body>
    </html>
  );
}
